#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #
      #      #jpa ddl-auto
      #        #create: DROP 후 CREATE
      #        #create-drop: DROP 후 CREATE 후 DROP
      #        #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 삭제는 불가능)
        #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true

  #log
  output:
    ansi:
      enabled: always


# 이미지 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
      location: c:\\upload
      enabled: true
